import type { ContentItem, MetricsSnapshot } from "@/lib/types";
import { calculateDeadlines } from "@/lib/utils";
import { enrichPerformanceFromFinalMetrics } from "@/lib/kpi";

const d = (s: string) => new Date(s);

function baseBrief(publishDate: Date, format: ContentItem["format"]) {
  const dl = calculateDeadlines(publishDate, format);
  return {
    briefDeadline: dl.briefDeadline,
    productionDeadline: dl.productionDeadline,
    approvalDeadline: dl.approvalDeadline,
  };
}

function mk(
  partial: Omit<
    ContentItem,
    | "createdAt"
    | "updatedAt"
    | "briefDeadline"
    | "productionDeadline"
    | "approvalDeadline"
    | "slaPresetKey"
  > & { slaPresetKey?: ContentItem["slaPresetKey"] }
): ContentItem {
  const publishDate = partial.publishDate;
  const fmt = partial.format;
  const preset = partial.slaPresetKey;
  const dl = preset
    ? calculateDeadlines(publishDate, preset)
    : baseBrief(publishDate, fmt);
  const now = new Date();
  return {
    ...partial,
    slaPresetKey: preset ?? partial.slaPresetKey,
    briefDeadline: dl.briefDeadline,
    productionDeadline: dl.productionDeadline,
    approvalDeadline: dl.approvalDeadline,
    createdAt: now,
    updatedAt: now,
  };
}

function snapshot(reach: number, overrides: Partial<MetricsSnapshot> = {}): MetricsSnapshot {
  return {
    recordedAt: new Date(),
    reach,
    impressions: Math.round(reach * 1.15),
    likes: Math.round(reach * 0.05),
    comments: Math.round(reach * 0.012),
    shares: Math.round(reach * 0.018),
    saves: Math.round(reach * 0.032),
    linkClicks: Math.round(reach * 0.01),
    watchTimePercent: 72,
    ...overrides,
  };
}

const publishedOld = d("2026-03-15T18:00:00");

/** 15 รายการครอบคลุม Pillar / Status / Format / KPI scenarios */
export const SEED_DATA: ContentItem[] = [
  mk({
    id: "POST-001",
    pillar: "fact",
    contentType: "educational",
    format: "carousel",
    platform: ["instagram"],
    funnelStage: "awareness",
    topic: "Pickleball คืออะไร? อธิบายแบบเข้าใจใน 60 วินาที",
    angle: "ทำความเข้าใจพื้นฐานก่อนลงสนาม",
    targetAudience: "มือใหม่ 22-35 ในเมือง",
    hook: "ทำไมทุกคนถึงหันมาตี pickleball?",
    captionDirection: "บทนำสั้น + bullet 3 ข้อ",
    visualDirection: "กราฟิกมินิมอล โทนสี DINKR",
    cta: "เซฟไว้แล้วแชร์ให้เพื่อน",
    dos: ["ภาษาง่าย", "มีภาพประกอบชัด", "แท็กแบรนด์"],
    donts: ["ศัพท์เทคนิคเยอะ", "ยาวเกิน 10 สไลด์", "สีแยกจากแบรนด์"],
    referenceLinks: ["https://example.com/pickleball-101"],
    strategicNotes: "ช่วง Awareness",
    owner: "Gain",
    status: "idea",
    publishDate: d("2026-07-02"),
    publishTime: "18:00",
    kpiTargets: { reachTarget: 12000, impressionTarget: 15000 },
  }),

  mk({
    id: "POST-002",
    pillar: "micro_wellness",
    contentType: "inspirational",
    format: "static_post",
    platform: ["instagram", "facebook"],
    funnelStage: "awareness",
    topic: "สายตรงหลังเล่น Pickleball 10 นาที",
    angle: "Micro wellness หลังเวิร์ก",
    targetAudience: "ออฟฟิศเมือง",
    hook: "เหยียดแบบนี้สบายตัวขึ้นทันที",
    captionDirection: "ขั้นตอน 4 ท่า",
    visualDirection: "ภาพคู่กับเส้นประกอบ",
    cta: "ลองแล้วคอมเมนต์บอกผล",
    dos: ["โฟกัสฟอร์ม", "ไฟสว่างธรรมชาติ", "จบด้วยคำชวนเซฟ"],
    donts: ["ท่ายากเกินไป", "ข้อความบังภาพ", "ไม่มีคำเตือนก่อนออกกำลัง"],
    referenceLinks: [],
    strategicNotes: "",
    owner: "Dom",
    status: "in_brief",
    publishDate: d("2026-06-28"),
    publishTime: "12:30",
    kpiTargets: { reachTarget: 8000, impressionTarget: 9000 },
  }),

  mk({
    id: "POST-003",
    pillar: "sport",
    contentType: "educational",
    format: "reel",
    platform: ["tiktok", "instagram"],
    funnelStage: "consideration",
    topic: "5 วิธีจับแร็กเก็ตให้คุมบอลดีขึ้น",
    angle: "ท่าจับสำหรับมือใหม่",
    targetAudience: "คนหัดเล่นในเมือง",
    hook: "จับแบบนี้ถูกมั้ย? 🤔",
    captionDirection: "Hook → Demo → CTA เซฟ",
    visualDirection: "ถ่ายมือ + แร็กเก็ตจริง outdoor",
    cta: "เซฟ + แชร์ให้เพื่อนที่หัดเล่น",
    dos: ["ภาษาไทยง่ายๆ", "โชว์มือจับชัด", "Text overlay สั้น"],
    donts: ["ศัพท์เทคนิคหนัก", "สตูดิโอเกินไป", "โลโก้ใหญ่เกิน"],
    referenceLinks: [],
    strategicNotes: "",
    owner: "Gain",
    status: "in_production",
    slaPresetKey: "reel",
    publishDate: d("2026-06-20"),
    publishTime: "18:00",
    kpiTargets: {
      engagementRateTarget: 8,
      saveRateTarget: 5,
      shareRateTarget: 2,
      watchTimeTarget: 60,
    },
    revisionRound: undefined,
  }),

  mk({
    id: "POST-004",
    pillar: "recommend_review",
    contentType: "entertaining",
    format: "carousel",
    platform: ["instagram"],
    funnelStage: "consideration",
    topic: "รองเท้า Pickleball คู่นี้โดนใจคอร์ทในเมือง",
    angle: "รีวิวจับใจสายขับรถไปคอร์ท",
    targetAudience: "สายเล่นประจำสุดสัปดาห์",
    hook: "กันลื่นบนคอร์ทกลางห้างจริงมั้ย?",
    captionDirection: "สรุปจุดเด่น 4 ข้อ + ข้อควรรู้",
    visualDirection: "ภาพคู่เท้า + macro พื้นคอร์ท",
    cta: "คอมเมนต์ว่าคุณใช้รุ่นไหน",
    dos: ["ถ่ายแสงธรรมชาติ", "ใส่แท็กของจริง", "สรุปราคาชัด"],
    donts: ["ดิสสโทร์สเกินจริง", "ถ่ายในที่มืด", "ไม่บอกสภาพพื้นจริง"],
    referenceLinks: [],
    strategicNotes: "",
    owner: "Dom",
    status: "in_review",
    publishDate: d("2026-06-18"),
    publishTime: "19:00",
    kpiTargets: {
      engagementRateTarget: 7,
      saveRateTarget: 4,
      shareRateTarget: 2,
    },
  }),

  mk({
    id: "POST-005",
    pillar: "mood",
    contentType: "entertaining",
    format: "story",
    platform: ["instagram"],
    funnelStage: "consideration",
    topic: "ซ้อมลูกสั้นดึงคู่แข่งเข้าหน้าอกเบาๆ",
    angle: "Mood / Funny moment",
    targetAudience: "คนที่เล่นเป็นประจำ",
    hook: "เมื่อคิดว่าจะจบเร็ว… 😅",
    captionDirection: "Sticker + Poll เล่นไหม",
    visualDirection: "คลิปสั้น vertical",
    cta: "แท็กเพื่อนที่ชอบลูกสั้น",
    dos: ["เก็บเสียงคอร์ทจริง", "จังหวะตลกชัด", "ไม่เกิน 15 วิ"],
    donts: ["ภาพสั่นเกินไป", "ดูหมิ่นผู้เล่น", "โลโก้บังจอ"],
    referenceLinks: [],
    strategicNotes: "",
    owner: "Gain",
    status: "revision",
    revisionRound: "R1",
    publishDate: d("2026-06-14"),
    publishTime: "20:00",
    kpiTargets: {
      engagementRateTarget: 6,
      saveRateTarget: 3,
      watchTimeTarget: 55,
    },
  }),

  mk({
    id: "POST-006",
    pillar: "fun_content",
    contentType: "entertaining",
    format: "reel",
    platform: ["tiktok"],
    funnelStage: "conversion",
    topic: "Challenge: ตีโทษถ้าพลาดลูกสั้นแบบนี้",
    angle: "เกมทายผลมีของรางวัลเล็ก",
    targetAudience: "สายคอนเทนต์ไวรัล",
    hook: "พลาดลูกนี้ = โทษตามกติกา!",
    captionDirection: "ชวนคอมเมนต์ทายผล",
    visualDirection: "คัตเร็ว + เสียงชัด",
    cta: "ทัก DM คำว่า “เล่น”",
    dos: ["ชัดเจนเรื่องกติกา", "CTA ชัด", "แท็กคอร์ทร่วม"],
    donts: ["อันตรายเกินไป", "เบลอใบหน้าคนอื่นไม่ขอ", "ยาวเกิน 35 วิ"],
    referenceLinks: [],
    strategicNotes: "",
    owner: "Dom",
    status: "pending_approval",
    slaPresetKey: "reel",
    publishDate: d("2026-06-22"),
    publishTime: "17:30",
    kpiTargets: {
      linkClicksTarget: 180,
      engagementRateTarget: 9,
    },
  }),

  mk({
    id: "POST-007",
    pillar: "fact",
    contentType: "educational",
    format: "static_post",
    platform: ["threads", "instagram"],
    funnelStage: "awareness",
    topic: "Pickleball มาจากไหน (ภาคเหนือของประวัติ)",
    angle: "ความรู้สั้นในโพสต์เดียว",
    targetAudience: "คนชอบเรื่องเล่าแปลกใหม่",
    hook: "ชื่อแปลก แต่ต้นกำเนิดไม่ใช่ pickle!",
    captionDirection: "Timeline สั้นๆ 4 bullet",
    visualDirection: "มินิมอล vector",
    cta: "แชร์ให้เพื่อนที่อยากรู้ที่มา",
    dos: ["ข้อเท็จจริงเช็คแล้ว", "ภาพคู่ข้อความ", "จบด้วยคำถามชวนคุย"],
    donts: ["copy วิกิยาวๆ", "ไม่ใส่ที่มา", "ฟอนต์เล็กเกินอ่านบนมือถือ"],
    referenceLinks: [],
    strategicNotes: "",
    owner: "Gain",
    status: "approved",
    publishDate: d("2026-06-10"),
    publishTime: "09:00",
    kpiTargets: { reachTarget: 15000 },
  }),

  mk({
    id: "POST-008",
    pillar: "micro_wellness",
    contentType: "inspirational",
    format: "carousel",
    platform: ["instagram"],
    funnelStage: "loyalty",
    topic: "Routine ก่อนลงคอร์ท 8 นาที",
    angle: "ภักดีแบรนด์ผ่านการดูแลตัวเอง",
    targetAudience: "ผู้เล่นประจำคอร์ทในเมือง",
    hook: "อย่าข้ามวอร์มนะ โดยเฉพาะข้อ 3",
    captionDirection: "ขั้นตอนพร้อมเช็คลิสต์",
    visualDirection: "ภาพ portrait + countdown slide",
    cta: "เซฟ Routine นี้ไว้ทุกครั้งก่อนเล่น",
    dos: ["ทำตามได้จริง", "ไม่ต้องมีอุปกรณ์เยอะ", "จบด้วยชวนแท็กเพื่อน"],
    donts: ["ท่าอันตราย", "ไม่เตือนคนที่มีเจ็บเข่า", "ยาวเกินไป"],
    referenceLinks: [],
    strategicNotes: "",
    owner: "Dom",
    status: "scheduled",
    publishDate: d("2026-06-09"),
    publishTime: "07:45",
    kpiTargets: { ugcVolumeTarget: 40 },
  }),

  mk({
    id: "POST-009",
    pillar: "sport",
    contentType: "promotional",
    format: "reel",
    platform: ["youtube", "instagram"],
    funnelStage: "conversion",
    topic: "ไฮไลต์คลินิกจับแร็กเก็ตกับโค้ช DINKR",
    angle: "ชวนจองคิวผ่านลิงก์ไบโอ",
    targetAudience: "มือใหม่ที่อยากเรียนเป็นระบบ",
    hook: "30 นาที เปลี่ยนวิธีคุมแร็กเก็ตของคุณ",
    captionDirection: "Before/After micro story",
    visualDirection: "มุมกว้างคอร์ท + close-up มือ",
    cta: "ลิงก์จองคิวในไบโอ",
    dos: ["โชว์โลโก้ท้ายสั้น", "ใส่ subtitle", "คำชวนที่ชัดเจน"],
    donts: ["โปรโมชันเกินจริง", "เสียงไม่ชัด", "ไม่บอกสถานที่ชัด"],
    referenceLinks: [],
    strategicNotes: "",
    owner: "Gain",
    status: "published",
    slaPresetKey: "reel",
    publishDate: d("2026-05-20T18:00:00"),
    publishTime: "18:00",
    publishedAt: d("2026-05-20T18:05:00"),
    kpiTargets: {
      engagementRateTarget: 8,
      saveRateTarget: 5,
      watchTimeTarget: 60,
    },
    performance: {
      snapshot24h: snapshot(5200),
      finalMetrics: snapshot(8500, {
        likes: 612,
        comments: 82,
        shares: 118,
        saves: 306,
        watchTimePercent: 74,
      }),
      whatWorked: "",
      whatDidnt: "",
      nextAction: "",
      overallRating: 4,
    },
  }),

  mk({
    id: "POST-010",
    pillar: "recommend_review",
    contentType: "entertaining",
    format: "story",
    platform: ["instagram"],
    funnelStage: "consideration",
    topic: "ลูกบอลคู่ไหนเหมาะคอร์ทในร่ม?",
    angle: "ถามความเห็นแฟนคลับ",
    targetAudience: "ผู้เล่นในเมือง",
    hook: "เลือกผิดบอล = เสียจังหวะทั้งเกม",
    captionDirection: "Poll + DM",
    visualDirection: "คู่บอลเทียบข้างกัน",
    cta: "โหวตใน Story",
    dos: ["ภาพชัด", "ถามเดียวตรงประเด็น", "ปิดท้ายด้วยคำขอบคุณ"],
    donts: ["ด่าแบรนด์อื่น", "ข้อความยาวใน story", "ไม่ตอบ DM"],
    referenceLinks: [],
    strategicNotes: "",
    owner: "Dom",
    status: "kpi_pending",
    publishDate: d("2026-04-25T12:00:00"),
    publishTime: "12:00",
    publishedAt: d("2026-04-25T12:10:00"),
    kpiTargets: {
      engagementRateTarget: 7,
      saveRateTarget: 4,
    },
    performance: undefined,
  }),

  mk({
    id: "POST-011",
    pillar: "mood",
    contentType: "entertaining",
    format: "carousel",
    platform: ["instagram"],
    funnelStage: "consideration",
    topic: "Playlist สายตีคอร์ทสุดสัปดาห์ 🎧",
    angle: "Mood content + Save",
    targetAudience: "Gen Z เล่นหลังเลิกงาน",
    hook: "เปิดเพลงนี้แล้วฟอร์มจะนุ่มขึ้น",
    captionDirection: "สไลด์ละ 1 เพลง + เหตุผล",
    visualDirection: "Gradient mood board",
    cta: "เซฟ Playlist นี้ไว้",
    dos: ["จัดลำดับเพลงชัด", "ไม่ละเมิดลิขสิทธิ์แคปชัน", "ใช้สีตามแบรนด์"],
    donts: ["แคปชันยาวเกิน", "ดันซื้อหูฟังเกินจริง", "มีถ้อยคำไม่เหมาะสม"],
    referenceLinks: [],
    strategicNotes: "",
    owner: "Gain",
    status: "published",
    publishDate: d("2026-04-01T19:00:00"),
    publishTime: "19:00",
    publishedAt: d("2026-04-01T19:01:00"),
    kpiTargets: {
      engagementRateTarget: 7,
      saveRateTarget: 5,
      shareRateTarget: 2,
    },
    performance: {
      snapshot24h: snapshot(4100),
      finalMetrics: snapshot(9200, {
        likes: 590,
        comments: 74,
        shares: 110,
        saves: 331,
      }),
      whatWorked:
        "มุม Playlist ทำให้ Save สูง โทนสีชัดและอ่านง่ายบนมือถือ",
      whatDidnt:
        "สไลด์ท้ายยาวไป คน swipe หลุดก่อนถึง CTA",
      nextAction:
        "ทำ Part 2 แยกตาม BPM และทดลอง CTA ที่สไลด์ 3",
      overallRating: 5,
    },
  }),

  mk({
    id: "POST-012",
    pillar: "fun_content",
    contentType: "entertaining",
    format: "ugc",
    platform: ["tiktok", "instagram"],
    funnelStage: "loyalty",
    topic: "รวมคลิปแฟนคลับโชว์ท่า Serve สุดปัง",
    angle: "UGC mashup",
    targetAudience: "Community DINKR",
    hook: "ท่าไหนในคลิปนี้ที่คุณอยากลอง?",
    captionDirection: "เครดิตผู้ส่งคลิป + ชวนส่งต่อ",
    visualDirection: "Split grid + transition สนุก",
    cta: "ส่งคลิปทัก DM",
    dos: ["ขออนุญาตทุกคลิป", "ใส่ watermark เบาๆ", "ขอบคุณชัดเจน"],
    donts: ["ใช้คลิปไม่ได้รับอนุญาต", "ซ่อนหน้าโดยไม่ขอ", "ดนตรีไม่มีสิทธิ์"],
    referenceLinks: [],
    strategicNotes: "",
    owner: "Dom",
    status: "published",
    publishDate: d("2026-03-28T16:00:00"),
    publishTime: "16:00",
    publishedAt: d("2026-03-28T16:02:00"),
    kpiTargets: {
      engagementRateTarget: 10,
      ugcVolumeTarget: 25,
    },
    performance: {
      snapshot24h: snapshot(6100),
      finalMetrics: snapshot(12100, {
        likes: 840,
        comments: 120,
        shares: 200,
        saves: 390,
        watchTimePercent: 68,
      }),
      whatWorked: "UGC แนวตลกทำให้แชร์พุ่ง และชุมชนรู้สึกมีส่วนร่วม",
      whatDidnt: "ท้ายคลิปชวนส่งซ้ำเร็วเกินไป คนบางกลุ่มไม่ทันอ่าน",
      nextAction:
        "เปิดแคมเปญรอบถัดไปพร้อมเทมเพลตชัด และปักหมุดท้ายคลิปนานขึ้น",
      overallRating: 4,
    },
  }),

  mk({
    id: "POST-013",
    pillar: "fact",
    contentType: "educational",
    format: "reel",
    platform: ["instagram"],
    funnelStage: "awareness",
    topic: "คำศัพท์คอร์ทที่ต้องรู้ก่อนเล่นกับเพื่อนใหม่",
    angle: "ศัพท์สั้นในคลิปเดียวจบ",
    targetAudience: "มือใหม่กำลังหาคอร์ทแรก",
    hook: "ถ้าได้ยินคำนี้ที่คอร์ท แปลว่าอะไร?",
    captionDirection: "คำศัพท์ละ 3 วินาที",
    visualDirection: "text overlay ใหญ่ชัด",
    cta: "เซฟศัพท์ชุดนี้",
    dos: ["พูดช้าพอฟังทัน", "มีตัวอย่างประโยค", "จบด้วยชวนคอมเมนต์"],
    donts: ["ศัพท์เยอะเกิน 15 คำ", "เสียงรบกวน", "ฟอนต์บางบนพื้นขาว"],
    referenceLinks: [],
    strategicNotes: "",
    owner: "Gain",
    status: "published",
    slaPresetKey: "reel",
    publishDate: publishedOld,
    publishTime: "18:00",
    publishedAt: publishedOld,
    kpiTargets: { reachTarget: 20000, engagementRateTarget: 6 },
    performance: undefined,
  }),

  mk({
    id: "POST-014",
    pillar: "sport",
    contentType: "educational",
    format: "carousel",
    platform: ["facebook", "instagram"],
    funnelStage: "consideration",
    topic: "เช็กลิสต์ก่อนแข่ง Pickleball มินิทัวร์นาเมนต์",
    angle: "เตรียมตัวครบในสไลด์เดียว",
    targetAudience: "สายแข่งระดับเริ่มต้น",
    hook: "ก่อนแข่งขอ 5 นาทีเช็กของในกระเป๋า",
    captionDirection: "สไลด์ละ 1 ข้อของควรพก",
    visualDirection: "Flat lay อุปกรณ์",
    cta: "แชร์ให้ทีมของคุณ",
    dos: ["ของจริงวางถ่าย", "เรียงตามลำดับการใช้", "มีช่องโน้ต"],
    donts: ["แบรนด์คู่แข่งโผล่ชัด", "ข้อความเล็ก", "ไม่มีสรุปท้าย"],
    referenceLinks: [],
    strategicNotes: "",
    owner: "Dom",
    status: "published",
    publishDate: d("2026-03-10T10:00:00"),
    publishTime: "10:00",
    publishedAt: d("2026-03-10T10:05:00"),
    kpiTargets: { engagementRateTarget: 7, saveRateTarget: 6 },
    performance: undefined,
  }),

  mk({
    id: "POST-015",
    pillar: "micro_wellness",
    contentType: "inspirational",
    format: "static_post",
    platform: ["instagram"],
    funnelStage: "awareness",
    topic: "ดื่มน้ำระหว่างเซต: ตารางจิบแบบโค้ชแนะนำ",
    angle: "Wellness content เบาๆ",
    targetAudience: "ผู้เล่นที่เล่นต่อเนื่อง 2 ชม.+",
    hook: "อย่ารอให้หิวน้ำถึงจะจิบ",
    captionDirection: "ตารางจิบสั้น + เหตุผล",
    visualDirection: "กราฟิกตารางสีพาสเทล",
    cta: "เซฟไว้ใช้วันแข่งจริง",
    dos: ["ตัวเลขชัด", "ไม่แพทย์เกินจริง", "มีดิสเคลเมอร์สั้น"],
    donts: ["คำแนะนำทางการแพทย์เต็มรูปแบบ", "ฟอนต์จิ๋ว", "ไม่มีที่มา"],
    referenceLinks: [],
    strategicNotes: "",
    owner: "Gain",
    status: "published",
    publishDate: d("2026-03-05T08:00:00"),
    publishTime: "08:00",
    publishedAt: d("2026-03-05T08:10:00"),
    kpiTargets: { reachTarget: 9000 },
    performance: undefined,
  }),
].map((item) =>
  item.performance?.finalMetrics ? enrichPerformanceFromFinalMetrics(item) : item
);
